### PR TITLE
Updated with larger storage numbers.

### PR DESCRIPTION
**Pull request by lukas-bernert**
# Description

Updated storage limit from 4TB to 10TB.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

### CODE REVIEW

**Review by jonatas — APPROVED** [review]

**Comment by jonatas** [comment]
Just a reminder that now the base is `master` not `latest`. Confirm @tedsczelecki?

**Comment by tedsczelecki** [comment]
> Just a reminder that now the base is `master` not `latest`. Confirm @tedsczelecki?

The base branch is latest, unless someone has changed that and if so I'll need to make edits to the CI

**Review by ryanbooz — APPROVED** [review]

**Comment by jonatas** [comment]
Thanks for confirming Ted. for some reason I thought we regularize it to `master`.

**Review by Loquacity — APPROVED** [review]
We should be using a {nbsp} between the integer and the unit, but that will need to done in the whole suite, so let's leave it like this for now, and I'll make a note to go back through later on.

**Review by mfreed — APPROVED** [review]

**Pull request merged**
