### PR TITLE
remove unintentional interpolate section

### PR DESCRIPTION
**Pull request by mirandaauhl**
# Description

remove unintentional interpolate section under histogram

# Version

latest

### CODE REVIEW

**Comment by ryanbooz** [comment]
Wait. What edits did I want?  😂

**Comment by mirandaauhl** [comment]
lololol I was hoping you wouldn't look too much into the branch
title 😂😂😂😂 I created the branch a while ago and had it open so I
thought I would just roll with it

**Comment by Loquacity** [comment]
Does this content belong somewhere else, or is it a dupe?

**Comment by mirandaauhl** [comment]
> Does this content belong somewhere else, or is it a dupe?

It is a duplicate! 😊

**Review by Loquacity — APPROVED** [review]

**Pull request merged**
