### PR TITLE
feat: add a guide on materialized ctes to query-data

### PR DESCRIPTION
**Pull request by rdmolony**
# Description

I just found out about materialized CTEs and thought I really should share this for people in similar situations. 

I'm consulting with a company that hides TimescaleDB behind a task queue, & some jobs were taking ages.  Using with cache as materialized ( ... )  resulted in a query that was taking days now takes 30 seconds!  These last few months I was getting frustrated that the Postgres query planner kept deciding on NestedLoop  joins.  

I see that you guys cover this in https://www.timescale.com/learn/how-to-use-common-table-expression-sql - however I reckon it could be covered in the `query-data` section of the docs too to force this on people?

# Links

~~Fixes #[insert issue link, if any]~~

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Comment by jonatas** [comment]
Amazing @rdmolony! @billy-the-fish will love it!

**Comment by billy-the-fish** [comment]
I love it indeed. @atovpeko can you review please.

**Comment by atovpeko** [comment]
Hi @rdmolony, I apologize that this has taken so long. We now have a cookbook in our docs, so that will probably be the ideal place for this guide. I have added it there, take a look: https://github.com/timescale/docs/pull/3654

**Comment by rdmolony** [comment]
Thanks @atovpeko I'll have a look!

**Pull request closed without merging**
