### PR TITLE
fix error in example code

### LINKED ISSUE #1666: [Content Bug] Syntax error at Partition in sample queries
The sample query on [this page ](https://docs.timescale.com/api/latest/hyperfunctions/counter_aggs/interpolated_delta/)doesn’t work due to a syntax error at  “PARTITION”
According to the [Postgres docs ](https://www.postgresql.org/docs/current/sql-expressions.html)it should be:
(PARTITION BY id ORDER by bucket)
as far as I see, this bug has spread to several  pages under [Hyperfunctions](https://docs.timescale.com/api/latest/hyperfunctions/) section.
Also, currently, interpolated_delta does not work without the prefix toolkit_experimental

# Describe the bug

Relevant [slack message](https://iobeam.slack.com/archives/C0J94TE4F/p1664523325137729)

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]
@DmitriiAn 

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

Fixes error in example code.

# Links

Fixes https://github.com/timescale/docs/issues/1666

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs/)

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

### CODE REVIEW

**Comment by Loquacity** [comment]
@DmitriiAn I'm not sure what other pages this might be in. I took a quick look through but couldn't spot any. Can you elaborate?

**Comment by DmitriiAn** [comment]
Hi @Loquacity , I should've documented it, sorry. I found it here 

- [interpolated_rate](https://docs.timescale.com/api/latest/hyperfunctions/counter_aggs/interpolated_rate/)
- [interpolated_average](https://docs.timescale.com/api/latest/hyperfunctions/time-weighted-averages/interpolated_average/)

**Comment by Loquacity** [comment]
Thanks @DmitriiAn ! Ready for you review now :)

**Review by Rajakavitha1 — APPROVED** [review]

**Review by DmitriiAn — APPROVED** [review]
looks good 👍

**Pull request merged**
