### PR TITLE
Add section about OOM killer

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

This is a good candidate for a Troubleshooting section, if we decide to create one.

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes https://github.com/timescale/docs/issues/358

### CODE REVIEW

**Review by jacobprall — APPROVED** [review]

**Review by clarkbw — APPROVED** [review]
giphy

**Comment by Loquacity** [comment]
@clarkbw Let me know when you're ready for this to merge 😉

**Comment by Loquacity** [comment]
@clarkbw ready for this to merge? September is nearly over ...

**Comment by clarkbw** [comment]
> @clarkbw ready for this to merge? September is nearly over ...

The OOM killer work hasn't been rolled out yet. We've pushed back into Oct. I think we'd need to change the article a bit to roll out now. If we had "here's how OOMs happen today" and "here's how OOMs will happen soon" we could roll this out. And when the feature completely rolls out (now expected for Nov) we adjust the article to use the past tense etc.

**Comment by Loquacity** [comment]
> > @clarkbw ready for this to merge? September is nearly over ...
> 
> The OOM killer work hasn't been rolled out yet. We've pushed back into Oct. I think we'd need to change the article a bit to roll out now. If we had "here's how OOMs happen today" and "here's how OOMs will happen soon" we could roll this out. And when the feature completely rolls out (now expected for Nov) we adjust the article to use the past tense etc.

I really like to try and avoid talking about things that may/may not happen in the future. Docs should always be present tense. We can leave this PR open if it's going to merge in October, or if you think it will be longer than a couple of weeks, we can close the PR but leave the branch around to pick up later on.

**Comment by Loquacity** [comment]
Opened a new PR to replace this one, since the content has moved on significantly.

**Pull request closed without merging**
