### PR TITLE
Update installation steps for Docker

### PR DESCRIPTION
**Pull request by dharmit**
# Description

I tried to install promscale using the [steps mentioned for Docker](https://docs.timescale.com/promscale/latest/installation/docker/#install-promscale-with-docker), but it failed because the flags were a little different from what's documented.

# Links

Fixes #[insert issue link, if any] - NA

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [x] Is the content free from typos?
- [x] Does the content use plain English?
- [x] Does the content contain clear sections for concepts, tasks, and references?
- [x] Are procedure and highlight tags used appropriately?
- [x] Has the index been updated appropriately?
- [x] Have any images been uploaded to the correct location, and are resolvable?
- [x] Are all links provided in reference style, and resolvable?
- [x] Have you checked the built version of this content?

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thank you for the PR @dharmit !!! Our team will review the updated content and merge the PR.

**Comment by Loquacity** [comment]
Just a note that the `Deploy docs to dev` job failing is expected behaviour. That's because the PR has been created on a fork.

**Review by Loquacity — APPROVED** [review]

**Comment by Rajakavitha1** [comment]
Validated the steps and checked the log as well. 
 ```Web endpoint for exposing Promscale's Prometheus metrics. [PROMSCALE_WEB_TELEMETRY_PATH] (default "/metrics")
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:314 msg="Update removed flag `db-ssl-mode` to new flag `db.ssl-mode`"
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:326 msg="Using removed flag `migrate` with an invalid value. Please update you configuration by using one of the startup flags."
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:314 msg="Update removed flag `db-password` to new flag `db.password`"
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:326 msg="Using removed flag `migrate` with an invalid value. Please update you configuration by using one of the startup flags."
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:314 msg="Update removed flag `db-port` to new flag `db.port`"
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:326 msg="Using removed flag `migrate` with an invalid value. Please update you configuration by using one of the startup flags."
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:314 msg="Update removed flag `db-name` to new flag `db.name`"
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:326 msg="Using removed flag `migrate` with an invalid value. Please update you configuration by using one of the startup flags."
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:314 msg="Update removed flag `db-host` to new flag `db.host`"
level=warn ts=2022-05-27T08:14:39.114Z caller=flags.go:326 msg="Using removed flag `migrate` with an invalid value. Please update you configuration by using one of the startup flags."
level=info ts=2022-05-27T08:14:39.114Z caller=main.go:26 msg="Version: 0.11.0, Commit Hash: f49197aac5f58755942fcbeb673271b7def122b2, Branch: HEAD"
level=error ts=2022-05-27T08:14:39.114Z caller=main.go:27 msg="cannot parse flags" err="using removed flags, please update to new flag names to proceed" ```

**Review by Rajakavitha1 — APPROVED** [review]

**Review by VineethReddy02 — APPROVED** [review]

**Comment by Rajakavitha1** [comment]
@Loquacity I think this PR has been validated and it is good for a merge.

**Pull request merged**
