### PR TITLE
[update] Tables and hypertables

### PR DESCRIPTION
**Pull request by Rajakavitha1**
# Description

[Short summary of why you created this PR]

# Links

Fixes https://github.com/timescale/docs/issues/2593

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Hi, @Loquacity !! I tried all combinations of \ and / in the code block none worked it was giving only / or no slash at all. So, I moved it out of the code block.

**Comment by Loquacity** [comment]
I think it should be `\` to escape the character, then `\` again to write it. But if it's not working, we'll have to go with the option of taking it out. This thing is gonna bug me until I die 🪦 Also, bad news, we probably need to fix these ones too: https://docs-dev.timescale.com/docs-gsg-typo-rajie/getting-started/gsg-typo-rajie/time-series-data/#ingesting-the-dataset

**Comment by Rajakavitha1** [comment]
> I think it should be `\` to escape the character, then `\` again to write it. But if it's not working, we'll have to go with the option of taking it out. This thing is gonna bug me until I die 🪦 Also, bad news, we probably need to fix these ones too: https://docs-dev.timescale.com/docs-gsg-typo-rajie/getting-started/gsg-typo-rajie/time-series-data/#ingesting-the-dataset

Let me try that and let you know and thank you for posting the other instances where the fix needs to be made.

**Comment by Rajakavitha1** [comment]
It worked @Loquacity 
Screenshot 2023-08-07 at 1 04 40 PM
Screenshot 2023-08-07 at 1 04 28 PM

**Pull request merged**
