### PR TITLE
Promscale cli and sql api reference pages

### PR DESCRIPTION
**Pull request by ramonguiu**
# Description

Continue moving PRs from Promscale repo to docs.timescale.com

This one contains the Promscale cli reference and the Promscale SQL functions reference. I am not adding them in the API reference section because I am not sure how to fit them in there for now. 

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

### CODE REVIEW

**Comment by Loquacity** [comment]
Need to fix tables and edit.

**Comment by Loquacity** [comment]
@ramonguiu @VineethReddy02 Is there any way we can get this into the format used in the API docs, even if we leave it in the Promscale secrtion for now? The template is at `api/_template.md`.

**Comment by ramonguiu** [comment]
> @ramonguiu @VineethReddy02 Is there any way we can get this into the format used in the API docs, even if we leave it in the Promscale secrtion for now? The template is at `api/_template.md`.

I am pretty sure we can convert the sql_api doc to use that template. Do you need us to do it or is this something you can help with?

The cli doc is quite different and I don't think that template is a good fit. Some examples of other cli docs:
- https://www.postgresql.org/docs/9.2/app-psql.html
- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html
- https://kubernetes.io/docs/reference/kubectl/kubectl/

**Comment by Loquacity** [comment]
> > @ramonguiu @VineethReddy02 Is there any way we can get this into the format used in the API docs, even if we leave it in the Promscale secrtion for now? The template is at `api/_template.md`.
> 
> I am pretty sure we can convert the sql_api doc to use that template. Do you need us to do it or is this something you can help with?
> 
> The cli doc is quite different and I don't think that template is a good fit. Some examples of other cli docs:
> 
> * https://www.postgresql.org/docs/9.2/app-psql.html
> * https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html
> * https://kubernetes.io/docs/reference/kubectl/kubectl/

Yeah, that's what I was thinking too. I'm not entirely certain how to handle this. @ryanbooz did you get a chance to look at this? Do you have any suggestions for me?

**Comment by ramonguiu** [comment]
@Loquacity @ryanbooz this PR is stalled since a couple of weeks. What's needed to unblock progress?

**Comment by Loquacity** [comment]
> @Loquacity @ryanbooz this PR is stalled since a couple of weeks. What's needed to unblock progress?

I'm not sure how to arrange this content, honestly. I'm hoping @ryanbooz has some ideas.

**Comment by ryanbooz** [comment]
I think the `page-index.js` is in shape now and the merge conflict is good to go. Please give it one last look @ramonguiu and/or @VineethReddy02 and give me a thumbs up here and we'll merge early tomorrow US eastern.

A coming UI update should widen the content area a bit which will make the table more readable, but I'm still generally in favor of finding a better way of showing this soon.

**Review by ryanbooz — APPROVED** [review]

**Pull request merged**
