### PR TITLE
Toolkit - hyperloglog content

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

Adds hyperloglog Toolkit content

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Partial: https://github.com/timescale/docs/issues/447

### CODE REVIEW

**Comment by Loquacity** [comment]
@davidkohn88 Adding you as an early reviewer, even though we're still in draft. Can you please provide me an example of running a hyperloglog query?

**Comment by Loquacity** [comment]
image

**Comment by jacobprall** [comment]
@Loquacity you can also add the toolkit tag up at the top!

**Comment by davidkohn88** [comment]
Took a quick look, do you mind if I pick up in a separate thing where we're going to prepare our next toolkit release? We have to stabilize some of this as well and add in a bit more explanation in parts. I think the plan is to have a branch where we grab the upcoming documentation for next toolkit release and have PRs to that.

**Comment by Loquacity** [comment]
New PR incoming.

**Pull request closed without merging**
