### PR TITLE
Revise placeholder parameters

### LINKED ISSUE #803: [Docs RFC] Standardize placeholder parameters in code
# Describe change in content, appearance, or functionality

Standardize placeholder parameters in code examples to use `<PLACEHOLDER_PARAM>`.

For example, `<TABLE_NAME>`, `<NEWER_THAN>`, and `<OLDER_THAN>` in:
```
SELECT decompress_chunk(i) from show_chunks('table_name', newer_than, older_than) i;
```

Also line-wrap code where possible to minimize horizontal scrolling in code boxes.

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

## Checklist for progress in checking the docs:

- [x] Install TimescaleDB
- [x] TimescaleDB overview
- [ ] TimescaleDB Getting started
- [ ] How-to guides
- [ ] Tutorials
- [ ] Code quick starts
- [ ] Contribution guides
- [ ] API reference
- [ ] Timescale Cloud
- [ ] Managed Service for TimescaleDB
- [ ] Promscale

### PR DESCRIPTION
**Pull request by charislam**
# Description

Standardize formatting of placeholder parameters
Where example arguments are used, make it clear that they are examples

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #803

### CODE REVIEW

**Comment by Loquacity** [comment]
@charislam What is the status of this PR?

**Comment by charislam** [comment]
> @charislam What is the status of this PR?

Still in progress! I stopped for a while because Ryan raised a question about how we wanted to do placeholder parameters. I think that is resolved now so I need to pick it up again.

**Comment by Loquacity** [comment]
@charislam this is getting pretty out of date now. Is it recoverable, do you think?

**Comment by charislam** [comment]
> @charislam this is getting pretty out of date now. Is it recoverable, do you think?

@Loquacity I'm just going to kill it. I still want to get back to this, but realistically it keeps getting kicked down the road for higher-priority items, and we're just getting more of those, not less. There's not a lot here, so I think fixing the conflicts is worse than starting from scratch in a few months

**Pull request closed without merging**
