### PR TITLE
remove comment

### PR DESCRIPTION
**Pull request by jacobprall**
# Description

[Short summary of why you created this PR]

# Version

Which documentation version does this PR apply to?

- [ ] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes #[insert issue link, if any]

### CODE REVIEW

**Comment by Loquacity** [comment]
> @Loquacity haven't we agreed to keep the 3 status (2 commented out) at all times? @jacobprall what is the purpose of this change?

Yep, that was my understanding. I'm wondering if maybe it broke something somehow? @jacobprall ?

**Comment by jacobprall** [comment]
The mdx parser didn't know how to handle it and thus broke - I'll look into if there's a work around

**Comment by Loquacity** [comment]
> The mdx parser didn't know how to handle it and thus broke - I'll look into if there's a work around

I've found that you need to have blank lines around comments for them to work. Did you try that?

**Comment by NunoFilipeSantos** [comment]
@jacobprall @Loquacity if that's the case maybe leave that as a comment on the file so when we do this in the future we don't forget.

**Pull request merged**
