### PR TITLE
Warn Windows users about  missing DLLs

### LINKED ISSUE #5631: [Bug]: error: PostgreSQL/15/lib/timescaledb-2.10.2.dll Unable to load library The specified module could not be found
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

Seems to be that the dependencies libssl-1_1-x64.dll and libcrypto-1_1-x64.dll are missing after installation. We were able to fix it by adding `C:\Program Files\Git\mingw64\bin` as system variable. Dlls are not present in the lib Folder of the Postgresql installation, only similarly named ones i.e. libssl-3-x64.dll were present. 

### TimescaleDB version affected

2.10.2

### PostgreSQL version used

15.2

### What operating system did you use?

Windows 10

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
Clean Windows machine without anything else apart from an installation of PostgreSQL.
```

### PR DESCRIPTION
**Pull request by rdmolony**
# Description

Hey there!

I was blocked for a few hours today by an issue with my `Windows` server environment.

`Windows` was linking to invalid `DLL` files which meant that `Postgres` couldn't load `TimescaleDB` even though the file existed. Specifically, it threw -  with `could not load library "C:/Program Files/PostgreSQL/14/lib/timescaledb-2.16.1.dll": The specified module could not be found.`. Very confusing!

This seems to come up every now & again on the GitHub (https://github.com/timescale/timescaledb/issues?q=load+library+dll+) so why not document it on the Windows guide?

# Links

Fixes https://github.com/timescale/timescaledb/issues/5631 & many other closed issues

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Comment by rdmolony** [comment]
It might be useful to link here from the FAQ of issues too

It might also be worth going into more detail on how DLLs are loaded. My issue was caused by an invalid/incompatible OpenSSL library that was accidentally on the User Path

**Review by billy-the-fish — APPROVED** [review]
LGTM

**Comment by billy-the-fish** [comment]
Hi there @rdmolony, thanks for adding this workaround to the documentation, much appreciated. Please tell me if you are ok with the updates I added. Soon as you are ok I will merge.

**Comment by rdmolony** [comment]
Thanks @billy-the-fish, looks good feel free to merge!

**Review by atovpeko — APPROVED** [review]

**Pull request merged**
