### PR TITLE
Update Tutorials Index page

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

With the tutorials reworked, it's time to update the index page! This is a quick and dirty version, until we can get design involved.

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Review by Rajakavitha1 — APPROVED** [review]

**Comment by Loquacity** [comment]
image

**Comment by Rajakavitha1** [comment]
> image

I love the &#x1F50B for energy and it is green!!!!

**Review by Rajakavitha1 — APPROVED** [review]

**Comment by Loquacity** [comment]
As requested, I've removed a few of the emojis (but preserved the green battery for @Rajakavitha1!)

image

**Comment by Rajakavitha1** [comment]
> As requested, I've removed a few of the emojis (but preserved the green battery for @Rajakavitha1!)
> 
> image

Thank you do much @Loquacity . I really love the green battery for energy. After all we are a company that care about our Planet :)

**Comment by Loquacity** [comment]
image (8)

**Pull request merged**
