### PR TITLE
Explain how encryption works in cloud

### PR DESCRIPTION
**Pull request by minkimipt**
# Description

We used a strong statement "All connections to Timescale are encrypted.", which is not correct. In fact customers can connect to their databases without using TLS and we need to address this in documentation. It's yet to be defined if we want to make this user configurable, but for now we need to update the doc to reflect the reality.

# Links

Fixes https://github.com/timescale/security-issues/issues/175

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Comment by minkimipt** [comment]
@contentana may I ask you to have a look and check the style and language? @clarkbw wanted to get your approval because you finally wanted to decide whether we productise optional unencrypted connections.

**Comment by contentana** [comment]
> @contentana may I ask you to have a look and check the style and language? @clarkbw wanted to get your approval because you finally wanted to decide whether we productise optional unencrypted connections.

Sure, let me have a look!

**Review by contentana — APPROVED** [review]
I made a couple of changes, I hope it's okay.

**Comment by clarkbw** [comment]
Let's talk more about this on Monday. I think the docs change here is fine. I want to discuss the changes coming.

**Comment by minkimipt** [comment]
Merging the doc changes for now and we'll return to this after there's more clarity about supporting this in ET.

**Pull request merged**
