### PR TITLE
Add note about segmentby for compression

### LINKED ISSUE #2458: [Docs RFC] Improve compression information
## Add emphasis to segmentby in our compression docs

Segmentby is one of the most important features for making good compression ratio for the data.

During the office hours, a community member mentioned our docs does not emphasize it that much.

We need to emphasize it to make people adopt the segmentby more often as it's very very important to have good compression ratios.

# Subject matter expert (SME)

@iroussos @noctarius

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

Adds a short note about segmentby for compression. 

@iroussos @noctarius Can you please let me know if there is extra that should be put in here, or if you think it also belongs on some other pages? I watched the office hours recording back, but wasn't certain where else this belongs, or what additional detail is required.

# Links

Fixes https://github.com/timescale/docs/issues/2458

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Comment by iroussos** [comment]
Thank you @Loquacity for adding this! I propose to merge this as is because it is already adding very important information/advise that we were not sharing with our users.

I think that we need to a separate page that will go deep into segment by, why it is important, how to set it up correctly and provide some examples and counterexamples for a few use cases. We can then link to it from the rest of the compression pages with a summary similar to what you added in this PR.

Some of that information is already scattered around various blog posts and some may have never been documented but there is internal knowledge, especially on our support team.  

@noctarius would you be interested in taking a stab at it? Pinging you as we were discussing this together, maybe someone else would be more suited to work on this.

**Comment by noctarius** [comment]
I would add one sentence more explaining why it is the most important thing. Something like "As explained in (the page explaining the compression arrays / batches) compression uses batches for high compression ratios, and segmentby groups data into those batches for efficient decompression and query speed."

WDYT?

**Comment by Loquacity** [comment]
> I would add one sentence more explaining why it is the most important thing. Something like "As explained in (the page explaining the compression arrays / batches) compression uses batches for high compression ratios, and segmentby groups data into those batches for efficient decompression and query speed."
> 
> WDYT?

Which page is that?

**Review by noctarius — APPROVED** [review]
For a first iteration that's good. We need to get more beefy content on how specifically this works, but for now that's perfect.

**Review by Rajakavitha1 — APPROVED** [review]
LGTM

**Pull request merged**
