### PR TITLE
Updates for usage based storage

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

Adds a partial and some small reworking for usage-based storage changes.

# Links

- Fixes https://github.com/timescale/docs-private/issues/138
- Fixes https://github.com/timescale/docs-private/issues/89

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Review by Rajakavitha1 — APPROVED** [review]
LGTM!

**Review by m0nae — APPROVED** [review]
LGTM 🚀

**Comment by carlotas19** [comment]
"Service Overview" needs a new screenshot—this has changed (now there's no disk capacity to manage and no autoscaling) 
Screen Shot 2023-06-14 at 5 57 55 PM

**Comment by Loquacity** [comment]
> "Service Overview" needs a new screenshot—this has changed (now there's no disk capacity to manage and no autoscaling) Screen Shot 2023-06-14 at 5 57 55 PM

We'll tackle the screenshots separately, they're next up on our list 👍

**Comment by Loquacity** [comment]
> "Storage autoscaling" needs to be removed from the get started page Screen Shot 2023-06-14 at 5 55 12 PM

@camilahirthe ?

**Comment by camilahirthe** [comment]
@carlotas19, what can be a good replacement for "Storage autoscaling"? I changed to "Storage usage-based" for now, but we can change it again

@charislam, here is the SVG and the png
Home illustration
Home illustration

**Review by Rajakavitha1 — APPROVED** [review]
LGTM

**Pull request merged**
