### PR TITLE
Add database roles and permissions page

### PR DESCRIPTION
**Pull request by ramonguiu**
# Description

Continue to move docs from Promscale repos to docs.timescale.com

# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

### CODE REVIEW

**Comment by Loquacity** [comment]
Needs editing.

**Comment by Loquacity** [comment]
@ramonguiu @VineethReddy02 Ready for your review.

**Review by charislam — APPROVED** [review]

**Review by jacobprall — APPROVED** [review]

**Review by ramonguiu — COMMENTED** [review]
Looks good to me!

**Comment by VineethReddy02** [comment]
LGTM!

**Review by VineethReddy02 — APPROVED** [review]

**Pull request merged**
