### PR TITLE
Candlestick tutorial technical check

### PR DESCRIPTION
**Pull request by aldia-ercule**
ran technical check, updated instructions and links accordingly

# Description

I ran a technical check on this tutorial and updated outdated instructions and links accordingly. Most of my work revolved around the prerequisite section and how there was no link or instructions on what data to use for the tutorial. As such, I relied on the Twelve Data zip file from the Candlestick tutorial on the live site, where I ran into the issue of the tick data .csv being incomplete and not having values for traded day volume. Because of this I could not run a technical check on the last section of the tutorial. 

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Comment by contentana** [comment]
@jonatas, can I please ask you to check this tutorial? @aldia-ercule reported that the data is incomplete. Do you know if we have this missing data somewhere else?

**Comment by jonatas** [comment]
Hi @aldia-ercule , I see `tutorials/OLD_grafana/visualizations/candlestick.md`.

Even being OLD, thanks for the fix  on the outdated stuff. Not sure if we have any non-OLD correspondent tutorial or that's all.

**Comment by aldia-ercule** [comment]
hi there @jonatas, would you like me to keep exploring different avenues to finish this technical check then? The tutorial on the live site says the data is sourced from Twelve Data, and I was curious about whether Timescale has a newer asset from them that includes traded day volume as a value?

**Comment by contentana** [comment]
Hi, Aldia! If @Jônatas Paganini ***@***.***> can't provide you
with a newer asset, let's try to complete the tutorial as best as we can,
even if we need to add/remove parts of it. Thanks!



Ana Margarida Tavares (she/her)
Sr. Content Marketing Manager | Timescale
Timescale.com <https://www.timescale.com/>

LinkedIn <https://www.linkedin.com/in/ana-margarida-tavares-b1228411/>
*My working hours may be different from your working hours.
Please don't feel you need to reply outside your regular work schedule.*

**Comment by jonatas** [comment]
Hi Aida, feel free to create an API key for twelve data. They have free keys. You can also use other APIs to load more data if you want to go deeper.

**Comment by aldia-ercule** [comment]
@jonatas I'll look into the API keys, thanks for the tip!
@contentana if the API keys don't end up working out, I'll finish up my edits without the day volume portion.

**Pull request closed without merging**
