### PR TITLE
Replace smart quotes with apostrophes

### PR DESCRIPTION
**Pull request by Joshua-Snapp**
# Description

This was created to replace smart quotes with apostrophes throughout the documentation. Smart quotes in code blocks will create problems when copied to a terminal. Also, smart quotes have been sprinkled throughout the regular text. Replacing them will help make quoting consistent throughout the documentation.
  
# Version

Which documentation version does this PR apply to?

- [x] Latest (Default)
- [ ] Version 1.7
- [ ] Older [specify]

# Links

Fixes https://github.com/timescale/docs/pull/894#issuecomment-1057641689

I'm totally flexible with this PR. Let me know if you would prefer to only change the smart quotes in the code blocks or would like some other approach. I don't mind adjusting what's in this PR or just closing it and letting the internal documentation team handle these changes.

### CODE REVIEW

**Comment by Loquacity** [comment]
Hi @Joshua-Snapp thanks so much for doing this, it's really helpful! If you can just sign the CLA, then we can get this merged.

**Comment by Joshua-Snapp** [comment]
Ugh...I think I created a problem. I accidentally authored and committed my two commits with my work email address, jksnapp@ncsu.edu. Then I signed the CLA with my personal GitHub account and personal email address. I think that's why the CLA isn't being recognized. I can't seem to change any values in the CLA. I'm new to those, so maybe I'm missing something. Maybe I should rebase and change my email address in the commits. Is that a reasonable way to fix this situation?

**Comment by Loquacity** [comment]
> Ugh...I think I created a problem. I accidentally authored and committed my two commits with my work email address, [jksnapp@ncsu.edu](mailto:jksnapp@ncsu.edu). Then I signed the CLA with my personal GitHub account and personal email address. I think that's why the CLA isn't being recognized. I can't seem to change any values in the CLA. I'm new to those, so maybe I'm missing something. Maybe I should rebase and change my email address in the commits. Is that a reasonable way to fix this situation?

I think you might need to `git commit --amend --author=<USERNAME>` to amend the commit and change the author to be your personal account. Might need a force commit, since the history changes. I'm not sure if that will kill this PR or not, though.

**Comment by Joshua-Snapp** [comment]
Okay. Looks like that fixed it. I reset my branch back to just my two commits, dropping your newer commits. Then I amended my commits with my personal email address for committer and author. Then I updated my branch with the newest commits from 'latest'. I think we're good to go.

**Review by Loquacity — APPROVED** [review]

**Review by jacobprall — APPROVED** [review]

**Pull request merged**
