### PR TITLE
Add release notes for 2.10.1

### PR DESCRIPTION
**Pull request by svenklemm**
# Description

[Short summary of why you created this PR]

# Links

Fixes #[insert issue link, if any]

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs/)

# Review checklists
Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

- [ ] Is the content technically accurate?
- [ ] Is the content complete?
- [ ] Is the content presented in a logical order?
- [ ] Does the content use appropriate names for features and products?
- [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

- [ ] Is the content free from typos?
- [ ] Does the content use plain English?
- [ ] Does the content contain clear sections for concepts, tasks, and references?
- [ ] Have any images been uploaded to the correct location, and are resolvable?
- [ ] If the page index was updated, are redirects required
      and have they been implemented?
- [ ] Have you checked the built version of this content?

### CODE REVIEW

**Review by iroussos — APPROVED** [review]

**Comment by iroussos** [comment]
@Loquacity @charislam should we combine the changes in this PR together with the ones in https://github.com/timescale/docs/pull/2097? Or first merge #2097 and then rebase and merge this PR on top of it?

**Comment by charislam** [comment]
@Loquacity you have the context around the new release note template, so I'm going to leave this one to you

@svenklemm just a note for the future, if you tag `timescale/docs-content`, it notifies like 30 people all the way up to Chad and Mike, `timescale/documentation` is a lot more tailored to the docs team (stupid naming I know, probably a legacy thing)

**Comment by Loquacity** [comment]
It depends on when you think this one is going to merge. If this merges within the next two weeks, we'll need to merge this one first then rebase the other one. Otherwise, we can merge the other one first.

**Comment by iroussos** [comment]
> It depends on when you think this one is going to merge. If this merges within the next two weeks, we'll need to merge this one first then rebase the other one.

@charislam @Loquacity those are release notes, so we should get them out sooner than that. @charislam Let's continue with this PR as usually and we can work on the low priority https://github.com/timescale/docs/pull/2097 at our own pace with @Loquacity :-)

**Review by charislam — APPROVED** [review]

**Comment by iroussos** [comment]
@charislam the PR looks good to me, can you please merge this as we are hitting the warnings limit with the linter? (this issue will go away with https://github.com/timescale/docs/pull/2097 🎉)

**Pull request merged**
