### PR TITLE
[Update] Compression pages

### PR DESCRIPTION
**Pull request by Rajakavitha1**
# Description

Drop the [Compress chunks](https://docs.timescale.com/use-timescale/latest/compression/compress-chunks/) page (which only references the compression explorer)
Move up the two [compression pages](https://docs.timescale.com/self-hosted/latest/compression/) under self-hosted in its place (no nesting needed - the manual decompress is at the same level as the other pages in the other hierarchy)

# Links

Fixes: https://github.com/timescale/docs-private/issues/142

# Writing help

For information about style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs/)

# Review checklists

Reviewers: use this section to ensure you have checked everything before approving this PR:

## Subject matter expert (SME) review checklist

*   [ ] Is the content technically accurate?
*   [ ] Is the content complete?
*   [ ] Is the content presented in a logical order?
*   [ ] Does the content use appropriate names for features and products?
*   [ ] Does the content provide relevant links to further information?

## Documentation team review checklist

*   [ ] Is the content free from typos?
*   [ ] Does the content use plain English?
*   [ ] Does the content contain clear sections for concepts, tasks, and references?
*   [ ] Have any images been uploaded to the correct location, and are resolvable?
*   [ ] If the page index was updated, are redirects required
      and have they been implemented?
*   [ ] Have you checked the built version of this content?

### CODE REVIEW

**Review by iroussos — CHANGES_REQUESTED** [review]
Thank you @Rajakavitha1,

You moved the [Manually compress chunks](https://docs.timescale.com/self-hosted/latest/compression/manual-compression/#manually-compress-chunks) page up from self hosted to Use Timescale > Compression, but you did not move the [About compression](https://docs.timescale.com/self-hosted/latest/compression/#about-compression) page up.

That page is the most important and should be first under [Compression](https://docs.timescale.com/use-timescale/latest/compression/#compression) with the other one on manual compression following

**Comment by iroussos** [comment]
To recap, as you also write on your description:

> 1. Drop the [Compress chunks](https://docs.timescale.com/use-timescale/latest/compression/compress-chunks/) page (which only references the compression explorer)
> 2. Move up the **!!two!!** [compression pages](https://docs.timescale.com/self-hosted/latest/compression/) under self-hosted in its place (no nesting needed - the manual decompress is at the same level as the other pages in the other hierarchy)

And I will add --> No need to rename them in any way. `About compression` and `Manual Compression` are as good as it can get. Let's just move the up and merge this PR, no need for another round of reviews

**Comment by Rajakavitha1** [comment]
Hi @iroussos  and @gina-alioto  we need your approvals before we can merge this PR.

**Review by gina-alioto — APPROVED** [review]

**Review by iroussos — APPROVED** [review]
Hey @Rajakavitha1, I can not see your changes in the [preview site](https://docs-dev.timescale.com/docs-compression-1-rajie/) but your changes seem reasonable and I trust that you have tested that the pages appear without issues. Approving on my side

**Pull request merged**
