### PR TITLE
Analytic edits

### PR DESCRIPTION
**Pull request by WireBaron**
Some edits (mostly renames) of Lana's branch adding in the analytics extension.

### CODE REVIEW

**Comment by JLockerman** [comment]
this PR supersedes https://github.com/timescale/docs/pull/107

**Comment by ryanbooz** [comment]
Hey guys, I'm not 100% on board with taking this approach and superseding the other PR. There is a LOT of conversation in that PR that's still relevant, but scrapping that in favor of this PR seems to cause more issues than it helps to get to the end goal. Why not just PR your renames/etc. into that branch?

**Review by Loquacity — APPROVED** [review]
Nice!

**Review by Loquacity — CHANGES_REQUESTED** [review]
Revoking my approve, just so we don't accidentally merge

**Comment by JLockerman** [comment]
@ryanbooz we're happy to move it back to the old PR; we did it this way because the branch required a rebase and we didn't want to risk overwriting @Loquacity's work while she was out.

@Loquacity do you want to merge in these commits or should I?

**Comment by Loquacity** [comment]
> 
> @Loquacity do you want to merge in these commits or should I?

If you can merge in this one to mine, then I can merge mine.

**Comment by JLockerman** [comment]
@Loquacity merged

**Pull request merged**
